### ISSUE TITLE
トピックの構造検討

### ISSUE THREAD

**Issue by arsnovare** [aptj-dev/ardupilot#10]
#### 参考ページ
http://dotnsf.blog.jp/archives/1035351522.html

**Comment by p-goudet** [comment]
MQTT topic管理による英語でwikiページを書きました。
https://github.com/aptj-dev/ardupilot/wiki/MQTT-Topic-management

**Comment by p-goudet** [comment]
![topic_structure](https://cloud.githubusercontent.com/assets/18257215/22689991/d1e14cb8-ed76-11e6-8103-7f90d7264fde.png)

**Comment by p-goudet** [comment]
![system_architecture](https://cloud.githubusercontent.com/assets/18257215/22689986/cdc7f118-ed76-11e6-8b90-745e79aa83c6.png)
