### ISSUE TITLE
4/1のデモ内容の検討

### ISSUE THREAD

**Issue by arsnovare** [aptj-dev/ardupilot#24]
### 4/1 軽井沢デモ内容の検討

これは、4/1に軽井沢で行われるプレスリリースでのデモ内容を検討するissueです。
以下、例です。皆さんのアイデアを聞いて、決めていきます。

##### 複数機で飛行デモ
複数のDrone を使用して、MQTTのシナリオコマンドで、飛行デモ行う。

##### 飛行ログの視覚化
ArduPilotのロケーションのログをWebSocketなどを使用して、ブラウザー上にGoogle Mapなどでリアルタイムで表示する。

**Comment by p-goudet** [comment]
![untitled diagram](https://cloud.githubusercontent.com/assets/18257215/23405660/9f7700f4-fdfe-11e6-8db7-3d03c562c60d.png)
