### ISSUE TITLE
サークルモードコマンド対応

### ISSUE THREAD

**Issue by arsnovare** [aptj-dev/ardupilot#25]

**Comment by norika-takumi** [comment]
サークルモードを追加しましたので、コマンドは下記の通りの種類が使用できます。
"mode guided"
"mode circle"
"param set circle_radius xxx"
xxxは半径
"mode land"
"mode stabilize"
"mode rtl"
"arm"
"disarm"
"takeoff xx"
xx は高度で "takeoff 20"という具合です。
"flyto x,y,z"
xは緯度、yは経度、zは高度を意味します。 "flyto 39.213,135.54,100.0" という具合です。
