### ISSUE TITLE
ダミーPublisherでpublishして欲しいトピックを提案してください

### ISSUE THREAD

**Issue by arsnovare** [aptj-dev/ardupilot#3]
【例】
/flightlog/navio2/accel/x
/flightlog/diy/gps/lat
/cmd/rc/3/1500

**Comment by tajisoft** [comment]
パブリッシャーツールを作ったので使ってください。jsなので多少のラグはご勘弁を。
http://160.16.96.11:8884/
Basic認証情報
ID: aptj
パス: aptj-mqtt

**Comment by arsnovare** [comment]
@tajisoft ツール使ってみました。素晴らしいです！
ありがとうございました。
