### ISSUE TITLE
MQTTライブラリーソースの配置場所の検討

### ISSUE THREAD

**Issue by arsnovare** [aptj-dev/ardupilot#7]
MQTTライブラリーのCソースを、ArduPilotのディレクトリツリー内でどこに配置するかを検討する。

現状、一番良さそうなのは、`module` 配下で、GitのSubmoduleとして取り込む方法が良いかも。

**Comment by p-goudet** [comment]
https://github.com/aptj-dev/ardupilot/blob/master/.gitmodules
