### ISSUE TITLE
MQTTを使用したサンプルソースの作成

### ISSUE THREAD

**Issue by arsnovare** [aptj-dev/ardupilot#9]
MQTTライブラリーを使用して、Pub/Subするサンプルソースを作成し、ArduPilotのソース内に配置する。

開発者は、それのサンプルを見ることにより、MQTTサーバへの接続や、Pub/Subの仕方がわかる。

**Comment by vs-tanaka** [comment]
# **1. 進捗**

現在の進捗状況は、送信は、現在地の緯度経度、高度を1秒おきに送信しています。
　ただし、現在のソースは、受信テスト中なので、送信機能を止めています。
受信は、mode guided, arm, takeoff, fryto, mode rtl　のコマンドを受信して実行できます。 
　ただし、fryto は固定の地点へのフライトです。その他、細かなオプションの指定はまだできません。
コマンド解析部分をUserCode.cppから ドライバの方に移動しました。
以下のURLが最新のコミットです。参考にしてください。
https://github.com/vs-tanaka/rmackay9-ardupilot/commit/fa499ec6cf1c095525a0b60dbde77d8a473690b8
# ２. コマンド案

コマンドは、この様に、ペイロードのテキスト中にコマンド名を記述したほうがやりやすいです。
コマンドの案としては、
"mode guided"
"mode rtl"
"arm throttle", "arm"
"takeoff xx"
xx は高度で "takeoff 20"という具合です。
"fryto x,y,z"
xは緯度、yは経度、zは高度を意味します。 "fryto 39.213,135.54,100.0" という具合です。

**Comment by norika-takumi** [comment]
commit の単位を修正して、この作業は終わりとします。
